apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-moran
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  labels:
    app: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
        tier: alpine
    spec:
      containers:
        - name: messaging
          image: redis:alpine