apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  labels:
    app: nginx-resolver
spec:
  type: ClusterIP
  ports:
    - port: 8888
      name: nginx-resolver-port
  selector:
    app: nginx-resolver
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-resolver
  name: nginx-resolver
spec:
  containers:
  - image: nginx
    name: nginx-resolver
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always