apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-moran
spec:
  containers:
  - name: redis-storage-moran
    image: redis:alpine
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}